package eg.gov.iti.jets.persistence.entity.enums;

public enum PrivilegeName {
    CREATE_TERMINATE_ASSIGN_INSTANCE,
    VIEW_TEMPLATES,
    MANAGE_TEMPLATE,
    START_STOP_VIEW_INSTANCE,
    MANAGE_STUDENTS,
    MANAGE_INSTRUCTORS,
    MANAGE_TRAINING_PROGRAMS,
    MANAGE_INTAKES,
    MANAGE_TRACKS,
    MANAGE_SUPERVISORS,
    MANAGE_TRAINING_MANAGERS,
    MANAGE_BRANCHES,
    MANAGE_ROLES,
    MANAGE_PRIVILEGES,
    VIEW_INSTANCE_LOGS;
}
