package eg.gov.iti.jets.persistence.entity.enums;

public enum PrivilegeName {

    CREATE_TERMINATE_ASSIGN_INSTANCE, //
    START_STOP_VIEW_INSTANCE,  //

    //MANAGE Privileges
    MANAGE_TEMPLATE, //
    MANAGE_STUDENTS, //
    MANAGE_INSTRUCTORS, //

    //MANAGE_TRAINING_PROGRAMS,
    //MANAGE_INTAKES,
    //MANAGE_TRACKS,
    // MANAGE_BRANCHES,
    MANAGE_SUPERVISORS, //
    MANAGE_TRAINING_MANAGERS, //

    MANAGE_USERS,

    MANAGE_ROLES,
    MANAGE_PRIVILEGES,



    //ADD Privileges
    ADD_EDIT_DELETE_TRAINING_PROGRAMS, //
    ADD_EDIT_DELETE_INTAKES,  //
    ADD_EDIT_DELETE_TRACKS, //
    ADD_EDIT_DELETE_BRANCHES, //

    //VIEW Privileges
    VIEW_TEMPLATE, //
    VIEW_BRANCHES, //
    VIEW_TRAINING_PROGRAMS, //
    VIEW_INTAKES, //
    VIEW_TRACKS, //
    VIEW_INSTANCE_LOGS,

}
