package eg.gov.iti.jets.persistence.entity.enums;

public enum PrivilegeName {

    CREATE_TERMINATE_ASSIGN_INSTANCE, // INSTRUCTOR ,SUPERVISOR
    START_STOP_VIEW_INSTANCE,  // INSTRUCTOR , SUPERVISOR, STUDENT

    //MANAGE Privileges
    MANAGE_TEMPLATES, // SUPERVISOR
    MANAGE_STUDENTS, // TRAINING MANAGER ,SUPER ADMIN
    MANAGE_STAFF, //  SUPER ADMIN
    MANAGE_ROLES, // SUPER ADMIN
    MANAGE_TRAINING_PROGRAMS, // SUPER ADMIN
    MANAGE_INTAKES,  // SUPER ADMIN
    MANAGE_TRACKS, // TRAINING MANAGER
    MANAGE_BRANCHES, // SUPER ADMIN
    MANAGE_PROFILE, // ALL

    //VIEW Privileges
    VIEW_TEMPLATES, // INSTRUCTOR ,SUPERVISOR
    VIEW_STUDENTS, // INSTRUCTOR , SUPERVISOR
    VIEW_USER, // SUPER ADMIN
    VIEW_INSTRUCTOR,//SUPERVISOR
    VIEW_ROLES, // SUPER ADMIN
    VIEW_STAFF, // SUPER ADMIN
    VIEW_PRIVILEGES, // SUPER ADMIN
    VIEW_BRANCHES, // SUPER ADMIN , TRAINING MANAGER , INSTRUCTOR ,SUPERVISOR
    VIEW_TRAINING_PROGRAMS, // SUPER ADMIN , TRAINING MANAGER , INSTRUCTOR ,SUPERVISOR
    VIEW_INTAKES, // SUPER ADMIN , TRAINING MANAGER , INSTRUCTOR ,SUPERVISOR
    VIEW_TRACKS, // SUPER ADMIN , TRAINING MANAGER , INSTRUCTOR ,SUPERVISOR
    VIEW_INSTANCE_LOGS, // SUPER
    VIEW_STATISTICS //SUPER ADMIN



}
